spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tables
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
      view:
        suffix: .html
server:
  port: 9799